CREATE DATABASE ESTACAO_METEREOLOGICA;

use ESTACAO_METEREOLOGICA;

CREATE TABLE TIPO_MEDICAO ( ID INT AUTO_INCREMENT NOT NULL, UNIDADE_MEDIDA VARCHAR(255) NOT NULL, PRIMARY KEY (ID) );

CREATE TABLE SENSOR ( ID INT AUTO_INCREMENT NOT NULL, Nome VARCHAR(255) NOT NULL, PRIMARY KEY (ID) );

CREATE TABLE MEDICOES ( ID INT AUTO_INCREMENT NOT NULL, Data DATETIME NOT NULL, VALOR VARCHAR(255) NOT NULL, PRIMARY KEY (ID) );

CREATE TABLE ESTACAO_PCD ( ID INT AUTO_INCREMENT NOT NULL, TEMPO_MEDICAO INT NOT NULL, IP VARCHAR(255) NOT NULL, PORTA VARCHAR(255) NOT NULL, CHAVE_ACESSO VARCHAR(255) NOT NULL, PRIMARY KEY (ID) );

CREATE TABLE SENSOR_INSTALADO ( ID INT AUTO_INCREMENT NOT NULL, ID_SENSOR INT NOT NULL, ID_TIPO_MEDICAO INT NOT NULL, ID_ESTACAO INT NOT NULL, ID_MEDICOES INT NOT NULL, PRIMARY KEY (ID) );

ALTER TABLE SENSOR_INSTALADO ADD CONSTRAINT tipo_medicao_sensor_instalado_fk FOREIGN KEY (ID_TIPO_MEDICAO) REFERENCES TIPO_MEDICAO (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE SENSOR_INSTALADO ADD CONSTRAINT sensor_sensor_instalado_fk FOREIGN KEY (ID_SENSOR) REFERENCES SENSOR (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE SENSOR_INSTALADO ADD CONSTRAINT medicoes_sensor_instalado_fk FOREIGN KEY (ID_MEDICOES) REFERENCES MEDICOES (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE SENSOR_INSTALADO ADD CONSTRAINT estacaopcd_sensor_fk FOREIGN KEY (ID_ESTACAO) REFERENCES ESTACAO_PCD (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;